### PR TITLE
Generate thumbnail image and summary statistics from resqml data

### PR DESCRIPTION
**Pull request by Skauvold**
The  `summarize-resqml-model.py` script reads one or more models on resqml format, and generates, for each model, a thumbnail image and a JSON file with containing summary statistics about the architectural elements in the model.

# Examples
### Thumbnail image
roda

### Summary stats
```
{
  "model_name": "roda",
  "archel_cell_counts": {
    "0": "11223602",
    "1": "637415",
    "2": "846402",
    "3": "320011",
    "4": "37031",
    "5": "641802",
    "6": "13631381"
  },
  "archel_cell_count_proportions": {
    "0": "41.06%",
    "1": "2.33%",
    "2": "3.10%",
    "3": "1.17%",
    "4": "0.14%",
    "5": "2.35%",
    "6": "49.86%"
  },
  "archel_volume_fractions": {
    "0": "1.56%",
    "1": "9.06%",
    "2": "11.92%",
    "3": "24.62%",
    "4": "4.86%",
    "5": "47.37%",
    "6": "0.62%"
  }
}
```

### Thumbnail image
sobrarbe

### Summary stats
```
{
  "model_name": "sobrarbe",
  "archel_cell_counts": {
    "0": "1627158",
    "1": "989947",
    "2": "205863",
    "3": "277528",
    "4": "226942",
    "5": "3197613",
    "6": "13570833"
  },
  "archel_cell_count_proportions": {
    "0": "8.10%",
    "1": "4.93%",
    "2": "1.02%",
    "3": "1.38%",
    "4": "1.13%",
    "5": "15.91%",
    "6": "67.53%"
  },
  "archel_volume_fractions": {
    "0": "0.96%",
    "1": "6.87%",
    "2": "5.81%",
    "3": "11.44%",
    "4": "8.07%",
    "5": "65.65%",
    "6": "1.20%"
  }
}
```

BEGIN_COMMIT_OVERRIDE
feat: Generate thumbnail image and summary statistics from resqml data
END_COMMIT_OVERRIDE

### CODE REVIEW

**Comment by Sinrefvol** [comment]
Do you know if it is possible to include x0, x1, y0 and y1 coordinates in summary? In case we decide to use this thumbnail for picking box area when estimating variogram etc?

**Comment by Sinrefvol** [comment]
@Skauvold

**Comment by Skauvold** [comment]
> Do you know if it is possible to include x0, x1, y0 and y1 coordinates in summary? In case we decide to use this thumbnail for picking box area when estimating variogram etc?

Yes, that's definitely possible. I'll look into it.

**Comment by Sinrefvol** [comment]
@Skauvold Another thing that was asked is if it is possible to make a legend of colours? Meaning, users would like to know what different colours in the thumbnail represent.

And maybe include legend description in the json file as well, including colour hex codes

**Comment by vegardkv** [comment]
Hi @Sinrefvol, I'll be following this up. on behalf of Jacob. I have adjusted the output a bit based on your comments above:
* I wasn't sure if you wanted coordinates on the thumbnail image (or only in the json file). If the thumbnail is intended to be a small image, I guess this does not make sense. Regardless, I have added them as well as grid lines, but can revert if you prefer
* I have not added a legend to the thumbnail, but it is added to the description file.

If this makes sense, I'll push the changes via Jacob's branch.

[Sobrarbe_048_Reference - coarse-sand_sed_and_obj_data_description.json](https://github.com/user-attachments/files/16905237/Sobrarbe_048_Reference.-.coarse-sand_sed_and_obj_data_description.json)
Sobrarbe_048_Reference - coarse-sand_sed_and_obj_data

**Comment by Sinrefvol** [comment]
@vegardkv Hei Vegard! We will most probably be presenting picture and overlaying it with custom coordinate picker in UI. So coordinate system on picture is probably redundant. If you could just comment it out and rather store the min/max coordinates in json file, that would be great

**Comment by vegardkv** [comment]
No problem. New iteration: I have removed the grid lines and padding, so that the bounds in the json file corresponds to the edges of the image. Is this perhaps more usable?
image

**Comment by Sinrefvol** [comment]
Yep, I think this should be good :)

**Comment by Sinrefvol** [comment]
@vegardkv if you could fix the poetry.lock conflict, then i will merge this PR into main

**Comment by Sinrefvol** [comment]
@vegardkv Still conflicted lockfile

**Comment by vegardkv** [comment]
@Sinrefvol Hopefully the conflict is properly resolved now

**Review by Sinrefvol — APPROVED** [review]

**Pull request merged**
